# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: ["labeled"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: print all things
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: EatsLemons/gha-kanban-next@v6.5
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
